// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNiKzyPAAEsT0O27rPD5v-4IRMPk-S_ZI',
    appId: '1:902990727240:web:28d31faca7099df0d6307d',
    messagingSenderId: '902990727240',
    projectId: 'hand-book-project',
    authDomain: 'hand-book-project.firebaseapp.com',
    storageBucket: 'hand-book-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwQN58ZlOvr_P2uLCjQZwONMfDwzmcGzM',
    appId: '1:902990727240:android:ea2d231ed68048b5d6307d',
    messagingSenderId: '902990727240',
    projectId: 'hand-book-project',
    storageBucket: 'hand-book-project.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNiKzyPAAEsT0O27rPD5v-4IRMPk-S_ZI',
    appId: '1:902990727240:web:bc407d6d1040aafbd6307d',
    messagingSenderId: '902990727240',
    projectId: 'hand-book-project',
    authDomain: 'hand-book-project.firebaseapp.com',
    storageBucket: 'hand-book-project.appspot.com',
  );

}